# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.db.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2020.07.07
# Revision...: --
# Purpose....: Docker compose file to create the DB containers used for
#              enterprise user security
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at https://oss.oracle.com/licenses/upl.
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3.5'
services:

# Database service as a single tenant database
  eus21c:
    image: oracle/database:21.3.0.0
    container_name: eus21c
    hostname: eus21c.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/eus/21c:/u01
      - ./cdb:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_EUS_CDB21_SQLNET}:1521"
    environment:
      DISPLAY: ${DOE_EUS_DISPLAY}:0
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TEUS21
      BASEDN: ${DOE_LAB_BASEDN}
      DOMAIN: ${DOE_LAB_DOMAIN}
      CUSTOM_RSP: /u01/common/etc
      ORADBA_DBC_FILE: custom_dbca21.0.0.dbc.tmpl
      ORADBA_RSP_FILE: dbca21.0.0.rsp.tmpl

networks:
  doe_lab_net:
    name: ${DOE_LAB_DOMAIN}
# - EOF -----------------------------------------------------------------