# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.oudsm.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2020.07.07
# Revision...: --
# Purpose....: Docker compose file to create a OUD Services Manager
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at https://oss.oracle.com/licenses/upl.
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3.5'
services:
# OUDSM service
  eusoudsm:
    image: oracle/oudsm:${DOE_EUS_OUDSM_VERSION}
    container_name: eusoudsm
    hostname: eusoudsm.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/eus/oudsm:/u01
      - ./oudsm:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_EUS_OUDSM_HTTP}:7001"
      - "${DOE_EUS_OUDSM_HTTPS}:7002"
    environment:
      INSTANCE_INIT: /u01/config
      ADMIN_PASSWORD: ${DOE_ADMIN_PASSWORD}

networks:
  doe_lab_net:
    name: ${DOE_LAB_DOMAIN}
# - EOF -----------------------------------------------------------------