# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2020.07.07
# Revision...: --
# Purpose....: Docker compose file to create a OUD NET instance used to
#              configure enterprise user security
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at https://oss.oracle.com/licenses/upl.
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3.5'
services:

# OUD LDAP service
  netoud:
    image: oracle/oud:${DOE_NET_OUD_VERSION}
    container_name: netoud
    hostname: netoud.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/net/oud:/u01
      - ./oud:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_NET_OUD_LDAP}:1389"
      - "${DOE_NET_OUD_LDAPS}:1636"
      - "${DOE_NET_OUD_ADMIN}:4444"
    environment:
      OUD_CUSTOM: 'TRUE'
      INSTANCE_INIT: /u01/config
      BASEDN: ${DOE_LAB_BASEDN}
      OUD_INSTANCE: oud_net
      ADMIN_PASSWORD: ${DOE_ADMIN_PASSWORD}

# Database service as a single tenant database
  netdb:
    image: oracle/database:${DOE_NET_SDB_VERSION}
    container_name: netdb
    hostname: netdb.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/net/sdb:/u01
      - ./sdb:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_NET_SDB_SQLNET}:1521"
    environment:
      DISPLAY: ${DOE_NET_DISPLAY}:0
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TNET01
      BASEDN: ${DOE_LAB_BASEDN}
      DOMAIN: ${DOE_LAB_DOMAIN}

# Database service as a single tenant database
    #   DISPLAY: ${DOE_NET_DISPLAY}:0
    #   INSTANCE_INIT: /u01/config
    #   ORACLE_SID: TNET01
    #   BASEDN: ${DOE_LAB_BASEDN}
    #   DOMAIN: ${DOE_LAB_DOMAIN}
    
networks:
  doe_lab_net:
    name: ${DOE_LAB_DOMAIN}
# - EOF -----------------------------------------------------------------