# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2020.07.07
# Revision...: --
# Purpose....: Docker compose file to create a OUD DBV instance used to
#              configure enterprise user security
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at https://oss.oracle.com/licenses/upl.
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3.5'
services:

# Database service as a single tenant database
  dbvcdb:
    image: oracle/database:${DOE_DBV_CDB_VERSION}
    container_name: dbvcdb
    hostname: dbvcdb.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/dbv/cdb:/u01
      - ./cdb:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_DBV_CDB_SQLNET}:1521"
      - "${DOE_DBV_CDB_HTTPS}:5500"
    environment:
      DISPLAY: ${DOE_DBV_DISPLAY}:0
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDBV01
      BASEDN: ${DOE_LAB_BASEDN}
      DOMAIN: ${DOE_LAB_DOMAIN}

  dbvsdb:
    image: oracle/database:${DOE_DBV_SDB_VERSION}
    container_name: dbvsdb
    hostname: dbvsdb.${DOE_LAB_DOMAIN}
    networks:
      - doe_lab_net
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - ${DOCKER_VOLUME_BASE}/doe/dbv/sdb:/u01
      - ./sdb:/u01/config
      - ./common:/u01/common
    ports:
      - "${DOE_DBV_SDB_SQLNET}:1521"
      - "${DOE_DBV_SDB_HTTPS}:5500"
    environment:
      DISPLAY: ${DOE_DBV_DISPLAY}:0
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDBV02
      BASEDN: ${DOE_LAB_BASEDN}
      DOMAIN: ${DOE_LAB_DOMAIN}
networks:
  doe_lab_net:
    name: ${DOE_LAB_DOMAIN}
# - EOF -----------------------------------------------------------------
